In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import pandas as pd
import re
#from selenium.webdriver.chrome.service import Service

In [2]:
#path
#ser_obj='path'
#driver=webdriver.Chrome(service=ser_obj)

website='https://www.99acres.com/'
driver=webdriver.Chrome()
driver.get(website)
driver.maximize_window()
#driver.quit()

In [3]:
#List containing the city name for searching
city=['Bangalore (All)','Pune']

In [4]:
#declaring empty list for appending the respective info
building_name=[]
price=[]
region=[]
location=[]
building_type=[]
near_by=[]
availability=[]
#list declaration for second data frame
floor_area=[]
app_name=[]
app_price=[]
area_ty=[]
loc_det=[]
app_size=[]
comp_sta=[]
app_status=[]
app_region=[]

In [5]:
#This function is used to select enter the city name and go to the relevant page of the website
def selecting_city():
        #Selecting data for a particular city
    element=driver.find_element(by=By.XPATH, value='//input[@class="component__searchInput"]')
    #selecting the city from the list declared above
    element.send_keys(city[0])
    #setting a waiting time for the drop down to appear
    time.sleep(1.5)
    #selecting the first element from the dropdown
    driver.find_element(By.XPATH,value='//li[@id="0"]').click()
    #hitting search button
    driver.find_element(By.XPATH,value='//button[@type="submit" and @variant="primaryRegular" ]').click()

In [6]:
def scroll_page_():
    for i in range(15):
        driver.execute_script("window.scrollBy(0, 4500)")
        #setting sleep/waiting time for the page to load
        time.sleep(1)

In [7]:
#function for collecting the data
def collecting_data():
    #setting some default value if it does not extract  any value
    res_name=res_price=res_loc=avl=temp='unknown'
    
        #extracting web element containing all property details
    val=driver.find_elements(By.XPATH,value='//section[@data-hydration-on-demand="true"]')
    #extracting web element containing each property detail
    res=val[6].find_elements(By.XPATH,value='//div[@style="height: 82%;"]')
    #extracting property name
    res_name=res[1].find_elements(By.XPATH,value='//*[@class="projectTuple__projectName  projectTuple__pdWrap20 ellipsis"]')
    #extracting property price
    res_price=res[1].find_elements(By.XPATH,value='//span[@class="list_header_bold configurationCards__srpPriceHeading configurationCards__configurationCardsHeading"]')
    #extracting property location
    res_loc=res[1].find_elements(By.XPATH,value='//h2[@class="projectTuple__subHeadingWrap body_med ellipsis"]')
    #extracting property avilability
    avl=val[6].find_elements(By.XPATH,value='//div[@class="projectTuple__carouselTag projectTuple__carouselShortlistTagPostioning "]')
    #extracting property and thier options
    temp=val[6].find_elements(By.XPATH,value='//div[@class="configurationCards__cardsWrapper configurationCards__srpCardStyle"]')

    #loops to append elements to list
    for x,y,z in zip(res_name,res_price,res_loc):
        building_name.append(x.text)
        price.append(y.text)
        location.append(z.text)
    for i in range(len(avl)):
        availability.append(avl[i].text)
    for x in temp:
        building_type.append(x.text)

In [8]:
#alternate function to collect data
def collecting_data2():
        #sub section
    val_2=driver.find_elements(By.XPATH,value='//div[@class="srpTuple__cardWrap tupleCardWrap"]')
    #location details
    loc_detail=val_2[0].find_elements(By.XPATH,value='//td[@class="srpTuple__tdClassPremium"]')
    #name of property
    name2=val_2[0].find_elements(By.XPATH,value='//td[@class="srpTuple__propertyPremiumHeading srpTuple__spacer10 srpTuple__tdClasstwoPremium "]')
    #price and size details
    detail=val_2[0].find_elements(By.XPATH,value='//tr[@class="srpTuple__flexWrap"]')
    #avilability status
    avil=val_2[0].find_elements(By.XPATH,value='//div[@class="f10 Ng100 srpTuple__postedByText ellipsis"]')
    #area specification
    area_spec=val_2[0].find_elements(By.XPATH,value='//td[@class="srpTuple__col title_semiBold  "]')
    
    for x,y,z,a,b in zip(name2,detail,loc_detail,avil,area_spec):
        app_name.append(x.text)
        loc_det.append(z.text)
        app_price.append(str(y.text).split('\n')[0]) 
        app_size.append(str(y.text).split('\n')[-2])

        try:
            floor_area.append(str(y.text).split('\n')[2])
        except:
            floor_area.append('unknown')

        temp1=z.text.split()[-3:]
        temp1=' '.join(temp1)
        app_region.append(temp1)

        temp2=str(a.text).split()[3:-2]
        temp2=' '.join(temp2)
        temp2='Since '+str(temp2)
        comp_sta.append(temp2)
        app_status.append('Ready To Move')
        area_ty.append(b.text.split(')')[-1])

In [9]:
def next_page():
    time.sleep(1)
    #code for scrolling to page to a particular height for entering the next button
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(1)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight-3300);")
    time.sleep(1)
    #command for next button
    driver.find_elements(By.XPATH,value='//a[@class="list_header_bold" and contains(text(),"Next Page")]')[0].click()

In [10]:
#enter the page number
pages=150
for i in range(pages):
    if i==0:
        selecting_city()
    else:
        try:
            print('scrapping page =',i)
            scroll_page_()
            collecting_data()
            next_page()
        except:
            print('exception')
            scroll_page_()
            collecting_data2()
            next_page()

scrapping page = 1
scrapping page = 2
scrapping page = 3
scrapping page = 4
scrapping page = 5
scrapping page = 6
scrapping page = 7
scrapping page = 8
scrapping page = 9
scrapping page = 10
scrapping page = 11
scrapping page = 12
scrapping page = 13
scrapping page = 14
scrapping page = 15
scrapping page = 16
scrapping page = 17
scrapping page = 18
scrapping page = 19
scrapping page = 20
scrapping page = 21
scrapping page = 22
scrapping page = 23
scrapping page = 24
scrapping page = 25
scrapping page = 26
scrapping page = 27
scrapping page = 28
scrapping page = 29
scrapping page = 30
scrapping page = 31
scrapping page = 32
scrapping page = 33
scrapping page = 34
scrapping page = 35
scrapping page = 36
scrapping page = 37
scrapping page = 38
scrapping page = 39
exception
scrapping page = 40
exception
scrapping page = 41
exception
scrapping page = 42
exception
scrapping page = 43
exception
scrapping page = 44
exception
scrapping page = 45
exception
scrapping page = 46
exception
scrapping page = 47
exception
scrapping page = 48
exception
scrapping page = 49
exception
scrapping page = 50
exception
scrapping page = 51
exception
scrapping page = 52
exception
scrapping page = 53
exception
scrapping page = 54
exception
scrapping page = 55
exception
scrapping page = 56
exception
scrapping page = 57
exception
scrapping page = 58
exception
scrapping page = 59
exception
scrapping page = 60
exception
scrapping page = 61
exception
scrapping page = 62
exception
scrapping page = 63
exception
scrapping page = 64
exception
scrapping page = 65
exception
scrapping page = 66
exception
scrapping page = 67
exception
scrapping page = 68
exception
scrapping page = 69
exception
scrapping page = 70
exception
scrapping page = 71
exception
scrapping page = 72
exception
scrapping page = 73
exception
scrapping page = 74
exception
scrapping page = 75
exception
scrapping page = 76
exception
scrapping page = 77
exception
scrapping page = 78
exception
scrapping page = 79
exception
scrapping page = 80
exception
scrapping page = 81
exception
scrapping page = 82
exception
scrapping page = 83
exception
scrapping page = 84
exception
scrapping page = 85
exception
scrapping page = 86
exception
scrapping page = 87
exception
scrapping page = 88
exception
scrapping page = 89
exception
scrapping page = 90
exception
scrapping page = 91
exception
scrapping page = 92
exception
scrapping page = 93
exception
scrapping page = 94
exception
scrapping page = 95
exception
scrapping page = 96
exception
scrapping page = 97
exception
scrapping page = 98
exception
scrapping page = 99
exception
scrapping page = 100
exception
scrapping page = 101
exception
scrapping page = 102
exception
scrapping page = 103
exception
scrapping page = 104
exception
scrapping page = 105
exception
scrapping page = 106
exception
scrapping page = 107
exception
scrapping page = 108
exception
scrapping page = 109
exception
scrapping page = 110
exception
scrapping page = 111
exception
scrapping page = 112
exception
scrapping page = 113
exception
scrapping page = 114
exception
scrapping page = 115
exception
scrapping page = 116
exception
scrapping page = 117
exception
scrapping page = 118
exception
scrapping page = 119
exception
scrapping page = 120
exception
scrapping page = 121
exception
scrapping page = 122
exception
scrapping page = 123
exception
scrapping page = 124
exception
scrapping page = 125
exception
scrapping page = 126
exception
scrapping page = 127
exception
scrapping page = 128
exception
scrapping page = 129
exception
scrapping page = 130
exception
scrapping page = 131
exception
scrapping page = 132
exception
scrapping page = 133
exception
scrapping page = 134
exception
scrapping page = 135
exception
scrapping page = 136
exception
scrapping page = 137
exception
scrapping page = 138
exception
scrapping page = 139
exception
scrapping page = 140
exception
scrapping page = 141
exception
scrapping page = 142
exception
scrapping page = 143
exception
scrapping page = 144
exception
scrapping page = 145
exception
scrapping page = 146
exception
scrapping page = 147
exception
scrapping page = 148
exception
scrapping page = 149
exception

In [11]:
#second dataframe
dat={'property_name':app_name,'size':app_size,'carpet_area':floor_area,'price':app_price,'avg_price':app_price,'location_details':loc_det,'region':app_region,'availability':app_status,'completion_status':comp_sta,'area_type':area_ty}
df1=pd.DataFrame(dat)

In [12]:
df1

,property_name,size,carpet_area,price,avg_price,location_details,region,availability,completion_status,area_type
0,,"1,200 sq.ft.","1,200 sq.ft.",₹ 90 L,₹ 90 L,Residential land / Plot in Yelahanka,Plot in Yelahanka,Ready To Move,"Since Dec, 2022",Plot Area
1,,"1,500 sq.ft.","1,500 sq.ft.",₹ 28.5 L,₹ 28.5 L,Residential land / Plot in Nandi Hills,in Nandi Hills,Ready To Move,"Since Dec, 2022",Plot Area
2,karnataka suvarna bhoomi,"1,200 sq.ft.","1,200 sq.ft.",₹ 14.39 L,₹ 14.39 L,Residential land / Plot in Ramanagara,Plot in Ramanagara,Ready To Move,"Since Nov, 2022",Plot Area
3,Tata New Haven\n4.4\n★,2 BHK,"1,163 sq.ft.",₹ 62 L,₹ 62 L,2 BHK Apartment in Tumkur Road,in Tumkur Road,Ready To Move,"Since Jan, 2023 by RERA",Super built-up Area
4,L and T Raintree Boulevard\n4.2\n★,3 BHK,"1,985 sq.ft.",₹ 2.35 Cr,₹ 2.35 Cr,3 BHK Apartment in Hebbal,Apartment in Hebbal,Ready To Move,"Since Sep, 2022",Super built-up Area
...,...,...,...,...,...,...,...,...,...,...
1146,Vaishnavi Terraces,3 BHK,"2,536 sq.ft.",₹ 2.65 Cr,₹ 2.65 Cr,4 Bedroom House in Whitefield,House in Whitefield,Ready To Move,"Since Jan, 2023 by RERA",Super built-up Area
1147,Prestige Falcon City\n4.6\n★,3 BHK,"2,104 sq.ft.",₹ 2.8 Cr,₹ 2.8 Cr,Residential land / Plot in Chikkajala,Plot in Chikkajala,Ready To Move,"Since Dec, 2022 by RERA",Super built-up Area
1148,Prestige Falcon City\n4.6\n★,4 BHK,"2,726 sq.ft.",₹ 3.5 Cr,₹ 3.5 Cr,Residential land / Plot in R.T. Nagar,in R.T. Nagar,Ready To Move,"Since Nov, 2022 by RERA",Super built-up Area
1149,Sobha Lifestyle,5 BHK,"10,000 sq.ft.",₹ 7.98 Cr,₹ 7.98 Cr,3 BHK Apartment in Jalahalli East,in Jalahalli East,Ready To Move,"Since Oct, 2022",Plot Area
1150,Sobha HRC Pristine,3 BHK,"1,892 sq.ft.",₹ 2.59 Cr,₹ 2.59 Cr,3 BHK Apartment in Dollar Scheme Colony,Dollar Scheme Colony,Ready To Move,"Since Nov, 2022",Super built-up Area

In [13]:
#creating the dataset
data={'Property_name':building_name,'Price':price,'Location_details':location,'Building_Type':building_type}
df=pd.DataFrame(data)
#creating the feature called region (extracted the last 2 words from the loaction details column)
for i in range(len(df)):
    region.append(df['Location_details'][i].split()[-2]+' '+df['Location_details'][i].split()[-1])
df['region']=region
#dropping the row with null in building type
df.drop(df[df['Building_Type']==''].index,axis=0,inplace=True)
df['availability_of_building']=availability
#extracting current building status and info regarding the finishing/finished date of construction
df['availability']=df['availability_of_building'].map(lambda x:x.split('\n')[0])
df['completion_status']=df['availability_of_building'].map(lambda x:x.split('\n')[-1])
df.drop('availability_of_building',axis=1,inplace=True)
df['completion_status']=df['completion_status'].str.replace('Ready To Move','unknown')

#resetting the index
df=df.reset_index()
df.drop('index',axis=1,inplace=True)

In [14]:
df

,Property_name,Price,Location_details,Building_Type,region,availability,completion_status
0,Kumar Prospera,₹ 90.74 L - 1.34 Cr,"2, 3 BHK Apartment in Hennur Road Bangalore North","2 BHK\nApartment\nSuper Built-up Area\n1,138 -...",Bangalore North,Under Construction,"(Completion in Jun, 2025)"
1,Vaishnavi Serene,₹ 45.57 - 79.04 L,"1, 2, 3 BHK Apartment in Yelahanka Bangalore N...",1 BHK\nApartment\nSuper Built-up Area\n635 - 6...,Bangalore North,Ready To Move,unknown
2,Jhanavi Noreste,₹ 53.55 - 63 L,"2, 3 BHK Apartment in Sarjapur Road Bangalore ...","2 BHK\nApartment\nSuper Built-up Area\n1,190 -...",Bangalore East,Under Construction,"(Completion in Mar, 2025)"
3,Pariwar Wise Palmsprings,₹ 68 - 91.56 L,"2, 3 BHK Apartment in Sarjapur Road Bangalore ...","2 BHK\nApartment\nSuper Built-up Area\n1,140 -...",Bangalore East,Under Construction,"(Completion in Dec, 2023)"
4,Assetz 63 Degree East,₹ 32 L - 2.01 Cr,"1, 2, 3, 4 BHK Apartment in Sarjapur Road Bang...",1 BHK\nApartment\nSuper Built-up Area\n474 - 7...,Bangalore East,Partially Ready To Move,"(Completion in Jul, 2025)"
...,...,...,...,...,...,...,...
474,Purva Sparkling Springs,₹ 3.15 - 4.37 Cr,"3, 4 BHK Villa in Bannerghatta Road Bangalore ...","3 BHK\nVilla\nBuilt-up Area\n2,611 - 3,622.33 ...",Bangalore South,New Launch,"(Completion in Jun, 2027)"
475,Global White Pearl,Price on request,Land in Sarjapur Road Bangalore East,"Land\nPlot Area\n1,162 - 1,937 sq.ft.\n(107.95...",Bangalore East,Ready To Move,"(Since Aug, 2021)"
476,Mantri Hills,₹ 42 - 52 L,Land in Nandi Hills Bangalore North,"Land\nPlot Area\n1,200 - 1,500 sq.ft.\n(111.48...",Bangalore North,Ready To Move,unknown
477,Global Golden Pearl,₹ 1.5 - 2.2 Cr,"3, 5 BHK Villa in Sarjapur Road Bangalore East","3 BHK\nVilla\nBuilt-up Area\n2,400 sq.ft.\n(22...",Bangalore East,Ready To Move,"(Since Jan, 2017)"
478,Geown Oasis,Price on request,"2, 3, 4 BHK Villa in Sarjapur Bangalore East","2 BHK\nVilla\nBuilt-up Area\n1,944 - 2,070 sq....",Bangalore East,Ready To Move,unknown

In [15]:
size1=[]
size2=[]
size3=[]

In [16]:
for i in range(len(df)):
    text=str(df['Building_Type'][i]).lower()
    ob1=re.compile(r'\d{1}\sbhk*|land')
    k=ob1.findall(text)
    if len(k)==0:
        size1.append('nil')
        size2.append('nil')
        size3.append('nil')
    elif len(k)==1:
        size1.append(ob1.findall(text)[0]+" "+ob1.split(text)[1])
        size2.append('nil')
        size3.append('nil')
    elif len(k)==2:
        size1.append(ob1.findall(text)[0]+" "+ob1.split(text)[1])
        size2.append(ob1.findall(text)[1]+" "+ob1.split(text)[2])
        size3.append('nil')
    else:
        size1.append(ob1.findall(text)[0]+" "+ob1.split(text)[1])
        size2.append(ob1.findall(text)[1]+" "+ob1.split(text)[2])
        size3.append(ob1.findall(text)[2]+" "+ob1.split(text)[3])

In [17]:
#adding the size details to the data frame
df['size1']=size1
df['size2']=size2
df['size3']=size3

In [18]:
name_property=[]
size=[]
carpet_area=[]
price_range=[]
avg_price=[]
location_details=[]
region_1=[]
availability_stat=[]
completion_stat=[]
area_type=[]

In [19]:
for i in range(len(df)):
    if df['size1'][i]!='nil':
        try:
            t1=df['Property_name'][i]                 #gets name of the property
            t2=df['size1'][i].split('\n')[0]          #get size details
            t3=df['size1'][i].split('\n')[3]          #gets carpet area
            t4=df['size1'][i].split('\n')[5]          #gets price range
            t5=df['Price'][i]                         #gets average price
            t6=df['Location_details'][i]              #gets location details
            t7=df['region'][i]                        #gets the region
            t8=df['availability'][i]                  #gets the availability status
            t9=df['completion_status'][i]             #gets completion status
            t10=df['size1'][i].split('\n')[2]         #gets area type info
        except:
            t1=t2=t3=t4=t5=t6=t7=t8=t9=t10='unknown'
        name_property.append(t1)
        size.append(t2)
        carpet_area.append(t3)
        price_range.append(t4)
        avg_price.append(t5)
        location_details.append(t6)
        region_1.append(t7)
        availability_stat.append(t8)
        completion_stat.append(t9)
        area_type.append(t10)
        
    if df['size2'][i]!='nil':
        try:
            t1=df['Property_name'][i]                 #gets name of the property
            t2=df['size2'][i].split('\n')[0]          #get size details
            t3=df['size2'][i].split('\n')[3]          #gets carpet area
            t4=df['size2'][i].split('\n')[5]          #gets price range
            t5=df['Price'][i]                         #gets average price
            t6=df['Location_details'][i]              #gets location details
            t7=df['region'][i]                        #gets the region
            t8=df['availability'][i]                  #gets the availability status
            t9=df['completion_status'][i]             #gets completion status
            t10=df['size2'][i].split('\n')[2]         #gets area type info
        except:
            t1=t2=t3=t4=t5=t6=t7=t8=t9=t10='unknown'
        name_property.append(t1)
        size.append(t2)
        carpet_area.append(t3)
        price_range.append(t4)
        avg_price.append(t5)
        location_details.append(t6)
        region_1.append(t7)
        availability_stat.append(t8)
        completion_stat.append(t9)
        area_type.append(t10)
        
    if df['size3'][i]!='nil':
        try:
            t1=df['Property_name'][i]                 #gets name of the property
            t2=df['size3'][i].split('\n')[0]          #get size details
            t3=df['size3'][i].split('\n')[3]          #gets carpet area
            t4=df['size3'][i].split('\n')[5]          #gets price range
            t5=df['Price'][i]                         #gets average price
            t6=df['Location_details'][i]              #gets location details
            t7=df['region'][i]                        #gets the region
            t8=df['availability'][i]                  #gets the availability status
            t9=df['completion_status'][i]             #gets completion status
            t10=df['size3'][i].split('\n')[2]         #gets area type info
        except:
            t1=t2=t3=t4=t5=t6=t7=t8=t9=t10='unknown'
        name_property.append(t1)
        size.append(t2)
        carpet_area.append(t3)
        price_range.append(t4)
        avg_price.append(t5)
        location_details.append(t6)
        region_1.append(t7)
        availability_stat.append(t8)
        completion_stat.append(t9)
        area_type.append(t10)

In [20]:
#creating the final data set
final_data=pd.DataFrame()
final_data['property_name']=name_property
final_data['size']=size
final_data['carpet_area']=carpet_area
final_data['price']=price_range
final_data['avg_price']=avg_price
final_data['location_details']=location_details
final_data['region']=region_1
final_data['availability']=availability_stat
final_data['completion_status']=completion_stat
final_data['area_type']=area_type

In [21]:
#dropping the data's which had issues during the transformation
final_data.drop(final_data[final_data['property_name']=='unknown'].index,axis=0,inplace=True)
final_data=final_data.reset_index()
final_data.drop('index',axis=1,inplace=True)

In [22]:
final_data

,property_name,size,carpet_area,price,avg_price,location_details,region,availability,completion_status,area_type
0,Kumar Prospera,2 bhk,"1,138 - 1,146 sq.ft.",₹ 90.74 - 91.85 l,₹ 90.74 L - 1.34 Cr,"2, 3 BHK Apartment in Hennur Road Bangalore North",Bangalore North,Under Construction,"(Completion in Jun, 2025)",super built-up area
1,Kumar Prospera,3 bhk,"1,461 - 1,710 sq.ft.",₹ 1.11 - 1.34 cr,₹ 90.74 L - 1.34 Cr,"2, 3 BHK Apartment in Hennur Road Bangalore North",Bangalore North,Under Construction,"(Completion in Jun, 2025)",super built-up area
2,Vaishnavi Serene,1 bhk,635 - 640 sq.ft.,₹ 45.57 - 45.93 l,₹ 45.57 - 79.04 L,"1, 2, 3 BHK Apartment in Yelahanka Bangalore N...",Bangalore North,Ready To Move,unknown,super built-up area
3,Vaishnavi Serene,2 bhk,"900 - 1,116 sq.ft.",₹ 62.67 - 77.71 l,₹ 45.57 - 79.04 L,"1, 2, 3 BHK Apartment in Yelahanka Bangalore N...",Bangalore North,Ready To Move,unknown,super built-up area
4,Jhanavi Noreste,2 bhk,"1,190 - 1,295 sq.ft.",₹ 53.55 - 58.28 l,₹ 53.55 - 63 L,"2, 3 BHK Apartment in Sarjapur Road Bangalore ...",Bangalore East,Under Construction,"(Completion in Mar, 2025)",super built-up area
...,...,...,...,...,...,...,...,...,...,...
759,Purva Sparkling Springs,4 bhk,"5,455.91 sq.ft.",price on request,₹ 3.15 - 4.37 Cr,"3, 4 BHK Villa in Bannerghatta Road Bangalore ...",Bangalore South,New Launch,"(Completion in Jun, 2027)",built-up area
760,Global Golden Pearl,3 bhk,"2,400 sq.ft.",₹ 1.5 cr,₹ 1.5 - 2.2 Cr,"3, 5 BHK Villa in Sarjapur Road Bangalore East",Bangalore East,Ready To Move,"(Since Jan, 2017)",built-up area
761,Global Golden Pearl,5 bhk,"3,800 sq.ft.",₹ 2.2 cr,₹ 1.5 - 2.2 Cr,"3, 5 BHK Villa in Sarjapur Road Bangalore East",Bangalore East,Ready To Move,"(Since Jan, 2017)",built-up area
762,Geown Oasis,2 bhk,"1,944 - 2,070 sq.ft.",price on request,Price on request,"2, 3, 4 BHK Villa in Sarjapur Bangalore East",Bangalore East,Ready To Move,unknown,built-up area
763,Geown Oasis,3 bhk,"1,881 - 2,655 sq.ft.",price on request,Price on request,"2, 3, 4 BHK Villa in Sarjapur Bangalore East",Bangalore East,Ready To Move,unknown,built-up area

In [23]:
data=final_data.copy()
data2=df1.copy()

In [25]:
data2

,property_name,size,carpet_area,price,avg_price,location_details,region,availability,completion_status,area_type
0,,"1,200 sq.ft.","1,200 sq.ft.",₹ 90 L,₹ 90 L,Residential land / Plot in Yelahanka,Plot in Yelahanka,Ready To Move,"Since Dec, 2022",Plot Area
1,,"1,500 sq.ft.","1,500 sq.ft.",₹ 28.5 L,₹ 28.5 L,Residential land / Plot in Nandi Hills,in Nandi Hills,Ready To Move,"Since Dec, 2022",Plot Area
2,karnataka suvarna bhoomi,"1,200 sq.ft.","1,200 sq.ft.",₹ 14.39 L,₹ 14.39 L,Residential land / Plot in Ramanagara,Plot in Ramanagara,Ready To Move,"Since Nov, 2022",Plot Area
3,Tata New Haven\n4.4\n★,2 BHK,"1,163 sq.ft.",₹ 62 L,₹ 62 L,2 BHK Apartment in Tumkur Road,in Tumkur Road,Ready To Move,"Since Jan, 2023 by RERA",Super built-up Area
4,L and T Raintree Boulevard\n4.2\n★,3 BHK,"1,985 sq.ft.",₹ 2.35 Cr,₹ 2.35 Cr,3 BHK Apartment in Hebbal,Apartment in Hebbal,Ready To Move,"Since Sep, 2022",Super built-up Area
...,...,...,...,...,...,...,...,...,...,...
1146,Vaishnavi Terraces,3 BHK,"2,536 sq.ft.",₹ 2.65 Cr,₹ 2.65 Cr,4 Bedroom House in Whitefield,House in Whitefield,Ready To Move,"Since Jan, 2023 by RERA",Super built-up Area
1147,Prestige Falcon City\n4.6\n★,3 BHK,"2,104 sq.ft.",₹ 2.8 Cr,₹ 2.8 Cr,Residential land / Plot in Chikkajala,Plot in Chikkajala,Ready To Move,"Since Dec, 2022 by RERA",Super built-up Area
1148,Prestige Falcon City\n4.6\n★,4 BHK,"2,726 sq.ft.",₹ 3.5 Cr,₹ 3.5 Cr,Residential land / Plot in R.T. Nagar,in R.T. Nagar,Ready To Move,"Since Nov, 2022 by RERA",Super built-up Area
1149,Sobha Lifestyle,5 BHK,"10,000 sq.ft.",₹ 7.98 Cr,₹ 7.98 Cr,3 BHK Apartment in Jalahalli East,in Jalahalli East,Ready To Move,"Since Oct, 2022",Plot Area
1150,Sobha HRC Pristine,3 BHK,"1,892 sq.ft.",₹ 2.59 Cr,₹ 2.59 Cr,3 BHK Apartment in Dollar Scheme Colony,Dollar Scheme Colony,Ready To Move,"Since Nov, 2022",Super built-up Area

In [34]:
final=pd.concat([data,data2],axis=0).reset_index()

In [37]:
final.drop('index',axis=1,inplace=True)

In [38]:
final

,property_name,size,carpet_area,price,avg_price,location_details,region,availability,completion_status,area_type
0,Kumar Prospera,2 bhk,"1,138 - 1,146 sq.ft.",₹ 90.74 - 91.85 l,₹ 90.74 L - 1.34 Cr,"2, 3 BHK Apartment in Hennur Road Bangalore North",Bangalore North,Under Construction,"(Completion in Jun, 2025)",super built-up area
1,Kumar Prospera,3 bhk,"1,461 - 1,710 sq.ft.",₹ 1.11 - 1.34 cr,₹ 90.74 L - 1.34 Cr,"2, 3 BHK Apartment in Hennur Road Bangalore North",Bangalore North,Under Construction,"(Completion in Jun, 2025)",super built-up area
2,Vaishnavi Serene,1 bhk,635 - 640 sq.ft.,₹ 45.57 - 45.93 l,₹ 45.57 - 79.04 L,"1, 2, 3 BHK Apartment in Yelahanka Bangalore N...",Bangalore North,Ready To Move,unknown,super built-up area
3,Vaishnavi Serene,2 bhk,"900 - 1,116 sq.ft.",₹ 62.67 - 77.71 l,₹ 45.57 - 79.04 L,"1, 2, 3 BHK Apartment in Yelahanka Bangalore N...",Bangalore North,Ready To Move,unknown,super built-up area
4,Jhanavi Noreste,2 bhk,"1,190 - 1,295 sq.ft.",₹ 53.55 - 58.28 l,₹ 53.55 - 63 L,"2, 3 BHK Apartment in Sarjapur Road Bangalore ...",Bangalore East,Under Construction,"(Completion in Mar, 2025)",super built-up area
...,...,...,...,...,...,...,...,...,...,...
1910,Vaishnavi Terraces,3 BHK,"2,536 sq.ft.",₹ 2.65 Cr,₹ 2.65 Cr,4 Bedroom House in Whitefield,House in Whitefield,Ready To Move,"Since Jan, 2023 by RERA",Super built-up Area
1911,Prestige Falcon City\n4.6\n★,3 BHK,"2,104 sq.ft.",₹ 2.8 Cr,₹ 2.8 Cr,Residential land / Plot in Chikkajala,Plot in Chikkajala,Ready To Move,"Since Dec, 2022 by RERA",Super built-up Area
1912,Prestige Falcon City\n4.6\n★,4 BHK,"2,726 sq.ft.",₹ 3.5 Cr,₹ 3.5 Cr,Residential land / Plot in R.T. Nagar,in R.T. Nagar,Ready To Move,"Since Nov, 2022 by RERA",Super built-up Area
1913,Sobha Lifestyle,5 BHK,"10,000 sq.ft.",₹ 7.98 Cr,₹ 7.98 Cr,3 BHK Apartment in Jalahalli East,in Jalahalli East,Ready To Move,"Since Oct, 2022",Plot Area
1914,Sobha HRC Pristine,3 BHK,"1,892 sq.ft.",₹ 2.59 Cr,₹ 2.59 Cr,3 BHK Apartment in Dollar Scheme Colony,Dollar Scheme Colony,Ready To Move,"Since Nov, 2022",Super built-up Area

In [39]:
final.to_csv('99acres.csv')

In [2]:
df3=pd.read_csv('99acres.csv')

In [5]:
df3

,Unnamed: 0,property_name,size,carpet_area,price,avg_price,location_details,region,availability,completion_status,area_type
0,0,Kumar Prospera,2 bhk,"1,138 - 1,146 sq.ft.",₹ 90.74 - 91.85 l,₹ 90.74 L - 1.34 Cr,"2, 3 BHK Apartment in Hennur Road Bangalore North",Bangalore North,Under Construction,"(Completion in Jun, 2025)",super built-up area
1,1,Kumar Prospera,3 bhk,"1,461 - 1,710 sq.ft.",₹ 1.11 - 1.34 cr,₹ 90.74 L - 1.34 Cr,"2, 3 BHK Apartment in Hennur Road Bangalore North",Bangalore North,Under Construction,"(Completion in Jun, 2025)",super built-up area
2,2,Vaishnavi Serene,1 bhk,635 - 640 sq.ft.,₹ 45.57 - 45.93 l,₹ 45.57 - 79.04 L,"1, 2, 3 BHK Apartment in Yelahanka Bangalore N...",Bangalore North,Ready To Move,unknown,super built-up area
3,3,Vaishnavi Serene,2 bhk,"900 - 1,116 sq.ft.",₹ 62.67 - 77.71 l,₹ 45.57 - 79.04 L,"1, 2, 3 BHK Apartment in Yelahanka Bangalore N...",Bangalore North,Ready To Move,unknown,super built-up area
4,4,Jhanavi Noreste,2 bhk,"1,190 - 1,295 sq.ft.",₹ 53.55 - 58.28 l,₹ 53.55 - 63 L,"2, 3 BHK Apartment in Sarjapur Road Bangalore ...",Bangalore East,Under Construction,"(Completion in Mar, 2025)",super built-up area
...,...,...,...,...,...,...,...,...,...,...,...
1910,1910,Vaishnavi Terraces,3 BHK,"2,536 sq.ft.",₹ 2.65 Cr,₹ 2.65 Cr,4 Bedroom House in Whitefield,House in Whitefield,Ready To Move,"Since Jan, 2023 by RERA",Super built-up Area
1911,1911,Prestige Falcon City\n4.6\n★,3 BHK,"2,104 sq.ft.",₹ 2.8 Cr,₹ 2.8 Cr,Residential land / Plot in Chikkajala,Plot in Chikkajala,Ready To Move,"Since Dec, 2022 by RERA",Super built-up Area
1912,1912,Prestige Falcon City\n4.6\n★,4 BHK,"2,726 sq.ft.",₹ 3.5 Cr,₹ 3.5 Cr,Residential land / Plot in R.T. Nagar,in R.T. Nagar,Ready To Move,"Since Nov, 2022 by RERA",Super built-up Area
1913,1913,Sobha Lifestyle,5 BHK,"10,000 sq.ft.",₹ 7.98 Cr,₹ 7.98 Cr,3 BHK Apartment in Jalahalli East,in Jalahalli East,Ready To Move,"Since Oct, 2022",Plot Area
1914,1914,Sobha HRC Pristine,3 BHK,"1,892 sq.ft.",₹ 2.59 Cr,₹ 2.59 Cr,3 BHK Apartment in Dollar Scheme Colony,Dollar Scheme Colony,Ready To Move,"Since Nov, 2022",Super built-up Area